In [1]:
!pip install missingno

Requirement already satisfied: missingno in c:\users\lidiv\anaconda3\lib\site-packages (0.5.2)
Requirement already satisfied: numpy in c:\users\lidiv\anaconda3\lib\site-packages (from missingno) (1.24.3)
Requirement already satisfied: matplotlib in c:\users\lidiv\anaconda3\lib\site-packages (from missingno) (3.7.1)
Requirement already satisfied: scipy in c:\users\lidiv\anaconda3\lib\site-packages (from missingno) (1.10.1)
Requirement already satisfied: seaborn in c:\users\lidiv\anaconda3\lib\site-packages (from missingno) (0.12.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\lidiv\anaconda3\lib\site-packages (from matplotlib->missingno) (1.0.5)
Requirement already satisfied: cycler>=0.10 in c:\users\lidiv\anaconda3\lib\site-packages (from matplotlib->missingno) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\lidiv\anaconda3\lib\site-packages (from matplotlib->missingno) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\lidiv\anaconda3\lib\site-packages (from matplotlib->missingno) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\lidiv\anaconda3\lib\site-packages (from matplotlib->missingno) (23.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\lidiv\anaconda3\lib\site-packages (from matplotlib->missingno) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\lidiv\anaconda3\lib\site-packages (from matplotlib->missingno) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\lidiv\anaconda3\lib\site-packages (from matplotlib->missingno) (2.8.2)
Requirement already satisfied: pandas>=0.25 in c:\users\lidiv\anaconda3\lib\site-packages (from seaborn->missingno) (1.5.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\lidiv\anaconda3\lib\site-packages (from pandas>=0.25->seaborn->missingno) (2022.7)
Requirement already satisfied: six>=1.5 in c:\users\lidiv\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib->missingno) (1.16.0)

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import matplotlib.ticker as mticks
import seaborn as sns


import missingno as miss
import datetime as dt
import statsmodels.tsa.api as tsa

plt.rcParams['figure.figsize'] = [10,5]

In [3]:
#  file path stored in the variable fpath
fpath = r'C:\Users\lidiv\core\project04\Crimes_-_2001_to_Present.csv'

In [4]:
# Read the CSV file
df = pd.read_csv(fpath)

In [5]:
# Display the first few rows of the DataFrame
df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,11037294,JA371270,03/18/2015 12:00:00 PM,0000X W WACKER DR,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,BANK,False,False,...,42.0,32.0,11,NaN,NaN,2015,08/01/2017 03:52:26 PM,NaN,NaN,NaN
1,11646293,JC213749,12/20/2018 03:00:00 PM,023XX N LOCKWOOD AVE,1154,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT $300 AND UNDER,APARTMENT,False,False,...,36.0,19.0,11,NaN,NaN,2018,04/06/2019 04:04:43 PM,NaN,NaN,NaN
2,11645836,JC212333,05/01/2016 12:25:00 AM,055XX S ROCKWELL ST,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,False,...,15.0,63.0,11,NaN,NaN,2016,04/06/2019 04:04:43 PM,NaN,NaN,NaN
3,11645959,JC211511,12/20/2018 04:00:00 PM,045XX N ALBANY AVE,2820,OTHER OFFENSE,TELEPHONE THREAT,RESIDENCE,False,False,...,33.0,14.0,08A,NaN,NaN,2018,04/06/2019 04:04:43 PM,NaN,NaN,NaN
4,11645601,JC212935,06/01/2014 12:01:00 AM,087XX S SANGAMON ST,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,RESIDENCE,False,False,...,21.0,71.0,11,NaN,NaN,2014,04/06/2019 04:04:43 PM,NaN,NaN,NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7935430 entries, 0 to 7935429
Data columns (total 22 columns):
 #   Column                Dtype
---  ------                -----
 0   ID                    int64
 1   Case Number           object
 2   Date                  object
 3   Block                 object
 4   IUCR                  object
 5   Primary Type          object
 6   Description           object
 7   Location Description  object
 8   Arrest                bool
 9   Domestic              bool
 10  Beat                  int64
 11  District              float64
 12  Ward                  float64
 13  Community Area        float64
 14  FBI Code              object
 15  X Coordinate          float64
 16  Y Coordinate          float64
 17  Year                  int64
 18  Updated On            object
 19  Latitude              float64
 20  Longitude             float64
 21  Location              object
dtypes: bool(2), float64(7), int64(3), object(10)
memory usage: 1.2+ GB

In [7]:
date_format = "%m/%d/%Y %H:%M:%S %p"

df['Datetime'] = pd.to_datetime(df['Date'], format=date_format)
df = df.sort_values('Datetime')
df

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,Datetime
2149322,1310741,G001135,01/01/2001 01:00:00 PM,047XX N ELSTON AV,0460,BATTERY,SIMPLE,RESIDENCE PORCH/HALLWAY,False,False,...,NaN,08B,1145613.0,1931427.0,2001,08/17/2015 03:03:40 PM,41.967833,-87.739978,"(41.96783306, -87.739978195)",2001-01-01 01:00:00
2173019,1323184,G017467,01/01/2001 01:00:00 PM,102XX S WOOD ST,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,RESIDENCE,False,False,...,NaN,26,1166196.0,1836771.0,2001,08/17/2015 03:03:40 PM,41.707671,-87.666996,"(41.707671475, -87.666996186)",2001-01-01 01:00:00
2266685,1311358,G001819,01/01/2001 01:00:00 PM,025XX W 45 PL,0610,BURGLARY,FORCIBLE ENTRY,RESIDENCE,False,False,...,NaN,05,1160341.0,1874463.0,2001,08/17/2015 03:03:40 PM,41.811226,-87.687401,"(41.811226273, -87.687401084)",2001-01-01 01:00:00
1685276,6154338,HP242745,01/01/2001 01:00:00 PM,065XX S KEDZIE AVE,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,...,66.0,06,1156214.0,1861165.0,2001,04/02/2008 01:05:33 AM,41.774819,-87.702896,"(41.774818809, -87.702896431)",2001-01-01 01:00:00
2240444,1315987,G001152,01/01/2001 01:00:00 AM,009XX N HUDSON AV,1310,CRIMINAL DAMAGE,TO PROPERTY,CHA APARTMENT,False,False,...,NaN,14,1173036.0,1906862.0,2001,08/17/2015 03:03:40 PM,41.899860,-87.639877,"(41.899860332, -87.63987705)",2001-01-01 01:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148846,13272224,JG498084,11/07/2023 12:00:00 AM,007XX E 71ST ST,0281,CRIMINAL SEXUAL ASSAULT,NON-AGGRAVATED,APARTMENT,False,False,...,69.0,02,1182491.0,1858108.0,2023,11/14/2023 03:42:12 PM,41.765861,-87.606664,"(41.765861124, -87.606664028)",2023-11-07 12:00:00
149340,13271835,JG497834,11/07/2023 12:00:00 AM,078XX S MAY ST,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,...,71.0,07,1170011.0,1852891.0,2023,11/14/2023 03:42:12 PM,41.751825,-87.652559,"(41.751825217, -87.65255864)",2023-11-07 12:00:00
149015,13269765,JG495532,11/07/2023 12:00:00 AM,047XX N LUNA AVE,0930,MOTOR VEHICLE THEFT,THEFT / RECOVERY - AUTOMOBILE,STREET,False,False,...,15.0,07,1138476.0,1931075.0,2023,11/14/2023 03:42:12 PM,41.967000,-87.766229,"(41.966999773, -87.766229274)",2023-11-07 12:00:00
149336,13269207,JG495042,11/07/2023 12:00:00 AM,025XX W OGDEN AVE,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,...,29.0,14,1159493.0,1893451.0,2023,11/14/2023 03:42:12 PM,41.863349,-87.689990,"(41.863348941, -87.689989856)",2023-11-07 12:00:00
148726,13273451,JG499744,11/07/2023 12:00:00 AM,038XX S WELLS ST,1563,SEX OFFENSE,CRIMINAL SEXUAL ABUSE,RESIDENCE,False,False,...,34.0,17,1175276.0,1879289.0,2023,11/14/2023 03:42:12 PM,41.824148,-87.632476,"(41.82414815, -87.632476338)",2023-11-07 12:00:00

In [8]:
#Form 1: Original individual crime data with a datetime index
df_individual = df.set_index('Date')

df_individual

,ID,Case Number,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,...,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,Datetime
Date,,,,,,,,,,,,,,,,,,,,,
01/01/2001 01:00:00 PM,1310741,G001135,047XX N ELSTON AV,0460,BATTERY,SIMPLE,RESIDENCE PORCH/HALLWAY,False,False,1722,...,NaN,08B,1145613.0,1931427.0,2001,08/17/2015 03:03:40 PM,41.967833,-87.739978,"(41.96783306, -87.739978195)",2001-01-01 01:00:00
01/01/2001 01:00:00 PM,1323184,G017467,102XX S WOOD ST,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,RESIDENCE,False,False,2213,...,NaN,26,1166196.0,1836771.0,2001,08/17/2015 03:03:40 PM,41.707671,-87.666996,"(41.707671475, -87.666996186)",2001-01-01 01:00:00
01/01/2001 01:00:00 PM,1311358,G001819,025XX W 45 PL,0610,BURGLARY,FORCIBLE ENTRY,RESIDENCE,False,False,914,...,NaN,05,1160341.0,1874463.0,2001,08/17/2015 03:03:40 PM,41.811226,-87.687401,"(41.811226273, -87.687401084)",2001-01-01 01:00:00
01/01/2001 01:00:00 PM,6154338,HP242745,065XX S KEDZIE AVE,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,831,...,66.0,06,1156214.0,1861165.0,2001,04/02/2008 01:05:33 AM,41.774819,-87.702896,"(41.774818809, -87.702896431)",2001-01-01 01:00:00
01/01/2001 01:00:00 AM,1315987,G001152,009XX N HUDSON AV,1310,CRIMINAL DAMAGE,TO PROPERTY,CHA APARTMENT,False,False,1823,...,NaN,14,1173036.0,1906862.0,2001,08/17/2015 03:03:40 PM,41.899860,-87.639877,"(41.899860332, -87.63987705)",2001-01-01 01:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11/07/2023 12:00:00 AM,13272224,JG498084,007XX E 71ST ST,0281,CRIMINAL SEXUAL ASSAULT,NON-AGGRAVATED,APARTMENT,False,False,322,...,69.0,02,1182491.0,1858108.0,2023,11/14/2023 03:42:12 PM,41.765861,-87.606664,"(41.765861124, -87.606664028)",2023-11-07 12:00:00
11/07/2023 12:00:00 AM,13271835,JG497834,078XX S MAY ST,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,612,...,71.0,07,1170011.0,1852891.0,2023,11/14/2023 03:42:12 PM,41.751825,-87.652559,"(41.751825217, -87.65255864)",2023-11-07 12:00:00
11/07/2023 12:00:00 AM,13269765,JG495532,047XX N LUNA AVE,0930,MOTOR VEHICLE THEFT,THEFT / RECOVERY - AUTOMOBILE,STREET,False,False,1623,...,15.0,07,1138476.0,1931075.0,2023,11/14/2023 03:42:12 PM,41.967000,-87.766229,"(41.966999773, -87.766229274)",2023-11-07 12:00:00
11/07/2023 12:00:00 AM,13269207,JG495042,025XX W OGDEN AVE,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,1023,...,29.0,14,1159493.0,1893451.0,2023,11/14/2023 03:42:12 PM,41.863349,-87.689990,"(41.863348941, -87.689989856)",2023-11-07 12:00:00
11/07/2023 12:00:00 AM,13273451,JG499744,038XX S WELLS ST,1563,SEX OFFENSE,CRIMINAL SEXUAL ABUSE,RESIDENCE,False,False,915,...,34.0,17,1175276.0,1879289.0,2023,11/14/2023 03:42:12 PM,41.824148,-87.632476,"(41.82414815, -87.632476338)",2023-11-07 12:00:00

In [9]:
# Save this DataFrame to a CSV file
df_individual.to_csv('individual_crime_data.csv')

In [10]:
# Form 2: Resampled/converted crime counts version (Each row is 1 day)

df['Date'] = pd.to_datetime(df['Date'])

In [11]:
# Set 'Date' column as the index
df.set_index('Date', inplace=True)

In [12]:
# Form 2: Resampled/converted crime counts version (Each row is 1 day)
df_counts = df.resample('D').size().reset_index(name='Crime_Counts')

In [13]:
# Display the resulting DataFrame
df_counts.head()

        Date  Crime_Counts
0 2001-01-01          1827
1 2001-01-02          1143
2 2001-01-03          1151
3 2001-01-04          1166
4 2001-01-05          1267

In [14]:
df_counts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8346 entries, 0 to 8345
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          8346 non-null   datetime64[ns]
 1   Crime_Counts  8346 non-null   int64
dtypes: datetime64[ns](1), int64(1)
memory usage: 130.5 KB

In [15]:
# Save this DataFrame to a CSV file
df_counts.to_csv('resampled_crime_counts.csv')

## Topic 1: Comparing Police Districts

## Which district had the most crimes in 2022?

In [17]:
# Filter data for the year 2022
df_2022 = df[df['Date'].dt.year == 2022]

KeyError: 'Date'